### ISSUE TITLE
Allow auto registering of health checks in full framework

### ISSUE THREAD

**Issue by alhardy** [AppMetrics/MicrosoftExtensions#2]
Dependency context does't seem to work when usign to find all health checks in referenced assemblies.

**Comment by relair** [comment]
This is closed but in App.Metrics.AspNetCore.Health.Endpoints version 2.0.0-preview1 the DependencyInjection and RegisterFromAssembly doesn't seem to work at all.
I have  a public class Inheriting from HealthCheck that implements CheckAsync but it doesn't get picket up (healthBuilder.HealthChecks are empty). 
As for details I have .Net Core 2 app targeted at full .Net framework.

**Comment by alhardy** [comment]
Hmm, OK, my unit test for this works but it's scanning the same assembly as the test itself :)

Any chance you'd be able to look into this one?

The code to look at would be [be](https://github.com/AppMetrics/MicrosoftExtensions/blob/dev/test/Health.Extensions.DependencyInjection.Facts/ServiceCollectionHealthBuilderExtensionsTests.cs#L32)

**Comment by relair** [comment]
I have found what was wrong, in https://www.app-metrics.io/web-monitoring/aspnet-core/health/ the documentation is incorrect/outdated. It seems that RegisterFromAssembly doesn't work if you don't call BuildAndAddTo.
Unfortunately I have found even more issues after that.
1. It seems that calling RegisterFromAssembly and BuildAndAddTo somehow tries to resolve all classes with HealthCheck in the name, regardless if they are inheriting from HealthCheck, causing potential errors on start.
2. BuildAndAddTo registers healthchecks as singletons, so I cannot use my own scoped services with them.

For now I have the following workaround (this is for someone who stumbles upon this looking for workaround):
```
// in Configure
ApplicationServices = app.ApplicationServices;
// in ConfigureServices
services.AddScoped<DatabaseHealthCheck>();
IHealthBuilder healthBuilder = AppMetricsHealth.CreateDefaultBuilder();
healthBuilder.HealthChecks.AddCheck("Database Health Check", CheckDatabaseHealth);
services.AddHealth(healthBuilder);

// Method in Startup
private ValueTask<HealthCheckResult> CheckDatabaseHealth()
{
    using (IServiceScope scope = ApplicationServices.CreateScope())
    {
        var databaseHealthCheck = scope.ServiceProvider.GetService<DatabaseHealthCheck>();`
        return databaseHealthCheck.CheckDatabaseStatus();
    }
}
```

I would expect dependency injection with AppMetrics to work similar to what I have done - resolving my healthchecks with their dependencies each time healthcheck endpoint is called. Unfortunately it is not the case right now.

**Comment by alhardy** [comment]
Thanks for the details and looking into this @relair 

> 1. It seems that calling RegisterFromAssembly and BuildAndAddTo somehow tries to resolve all classes with HealthCheck in the name, regardless if they are inheriting from HealthCheck, causing potential errors on start.

Ah that could be the case, I thought I changed this to check for class which inherit health check rather than ends with "HealthCheck". Will look into this one for the next release

> 2. BuildAndAddTo registers healthchecks as singletons, so I cannot use my own scoped services with them.

Yep, was tricky to do otherwise. Will have to review again for the details as memory isn't serving me. It could be less verbose than your work around to inject a `Func`

**Comment by alhardy** [comment]
Documentation updated

**Comment by alhardy** [comment]
> 1. It seems that calling RegisterFromAssembly and BuildAndAddTo somehow tries to resolve all classes with HealthCheck in the name...

Resolved
